[공통] 셀렉트 박스 구현
sprint-part3-team11/taskify pull request #5
Opened 2024-04-14 14:02 UTC by hijiyun

## 📌 주요 사항
- 아이콘들을 어떤 경로에 해도.. 어떤 방법으로 작성해도 자꾸 안 뜨길래, svg태그로 넣었습니다 ..

## 📷 스크린샷
**기본** 
![스크린샷 2024-04-14 오후 9 38 31](https://github.com/sprint-part3-team11/taskify/assets/114905530/75a8488a-1e20-4c6a-8393-abd44d72964b)

---

**셀렉트 박스 열었을 때**
![스크린샷 2024-04-14 오후 9 38 56](https://github.com/sprint-part3-team11/taskify/assets/114905530/fa5dec1d-68d6-496b-8e50-3e05c26d6e06)

---

**option값 클릭 했을 때**
![스크린샷 2024-04-14 오후 9 39 53](https://github.com/sprint-part3-team11/taskify/assets/114905530/32ac0959-df85-4fee-adb6-e0dc77dae4b1)

---

**모바일 반응형**
![스크린샷 2024-04-14 오후 11 02 16](https://github.com/sprint-part3-team11/taskify/assets/114905530/4e78f7c7-ce18-4a5c-86bf-61da3226c8be)

## 💬 리뷰 시 요구사항![선택]
`<SelectBox title={'담당자'} options={selectBoxOptions} whether={true} />
`
컴포넌트를 쓸 때 위처럼 쓰게 되는데, 
1. title은 "담당자", "상태" 가 있습니다.
2. option은 배열 내부에 객체로 value, label을 작성하게 되는데 value는 진짜 값을 나타내고, label은 화면에 보여지는 값 입니다.
3. whether은 placeholder의 여부입니다. title이 "상태" 일때는 whether을 false로 바꾸면 됩니다.
<br />

컴포넌트에서 value값과 label값을 추출해야 한다면, `option.value` , `option.lebel` 을 작성하면 됩니다. 

## #️⃣ 연관 이슈번호
이슈를 해결한 경우 👉🏻 close #3

2024-04-15 10:52 UTC, minjo0n61 approved these changes
고생하셨습니다!

2024-04-15 10:52 UTC, minjo0n61 commented on src/components/common/SelectBox.tsx
> +const SelectBox: React.FC<SelectBoxProps> = ({ title, options, whether }) => {
[P2]: 저희 컴포넌트 내보낼 때 function(함수 선언식)으로 내보내기로 했었는데 생각해보니까 저도 화살표 함수로 사용했어서 저희 둘 다 코드 바꿔야할 것 같아요!

2024-04-15 11:38 UTC, hijiyun commented on src/components/common/SelectBox.tsx
> +const SelectBox: React.FC<SelectBoxProps> = ({ title, options, whether }) => {
헉 완전 잊고 있었어요 알려주셔서 감사합니당 🥹

2024-04-15 16:30 UTC, sihyonn requested changes
지윤님 수고 많으셨어요!!
추진력이 이렇게 좋을수가...뚝딱뚝딱 착착착 진행하시는 모습이 보기 좋습니당👍🏻
저도 얼릉 따라갈게요 ㅎㅎ 리뷰 몇개 남겼는데 한번 반영해보시면 좋을 것 같아요오~~

2024-04-15 16:30 UTC, sihyonn commented on src/components/common/SelectBox.tsx
> +    background: ${theme.color.white};
[P2]
: theme의 경우 app에서 ThemeProvider를 통해 전역적으로 설정되어 있어요!
파일마다 import할 필요없이 theme 객체를 직접 접근하는 방법으로 하면 더 좋을 것 같아요:)

``` suggestion 
  background: ${({theme}) => theme.color.white}
```

2024-04-15 16:30 UTC, sihyonn commented on src/components/common/SelectBox.tsx
> +  `,
[P1]
: 팀원들과 같이 논의한 CSS 선언 순서에 따라 정렬해보시면 더 좋을 것 같아욥!! 😊

``` suggestion
   Text: styled.div<{ $gray?: boolean }>`
      flex: 3;
      overflow: hidden;
      margin: 0 0.625rem;

     color: ${({ theme, $gray }) => ($gray ? theme.color.gray : theme.color.body)};
     font-size: 1rem;
     font-weight: 300;
     text-overflow: ellipsis;
     white-spacr: nowrap;
```

2024-04-15 16:30 UTC, sihyonn commented on src/components/common/SelectBox.tsx
> +    line-height: normal;
[P1]
:`font-family`의 경우 기본 Pretendard로 GlobalStyle에 적용되어 있어서 명시해주시지 않아도 괜찮아요!
font-style도 마찬가지입니다! 또한 `line-height: normal`은 브라우저가 기본적으로 적용하기 때문에 따로 명시하지 않으셔두 되구, 특정 값이 있다면 명시해주시면 좋을 것 같아요~😆

2024-04-15 16:30 UTC, sihyonn commented on src/components/common/SelectBox.tsx
> +  }, []);
[P2]
: 요기는 다른 곳에서도 사용하기 좋을 것 같아서 커스텀 훅으로 분리해봐도 좋을 것 같아요~!~!
ref와 ref외부를 클릭시 수행할 callback을 받아서 

``` suggestion 
function useOutSideClick(ref: RefObject<HTMLElement>, callback: () => void) {
  const handleClick = useCallback(
    (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) callback?.();
    },
    [ref, callback]
  );
  useEffect(() => {
    window.addEventListener('mousedown', handleClick);
    return () => window.removeEventListener('mousedown', handleClick);
  }, [ref, callback, handleClick]);
}

``` 
이런식으로요!
그리고 셀렉트박스에서 지윤님이 설정한 `ref`랑 `setIsDropdownOpen(false)` 를 전달해 볼 수 있겠네요!

2024-04-15 16:30 UTC, sihyonn commented on src/components/common/SelectBox.tsx
> +  // whether가 false이고 선택된 옵션이 없으면 첫 번째 옵션을 선택한다.
[P3]
: whether가 어떤걸 의미하는지 이름만 보고는 파악하기 어려울 수도 있을 것 같아요!
조금 더 좋은 네이밍은 뭐가 있을까용 같이 고민해봅시댜!

2024-04-15 17:40 UTC, hijiyun commented on src/components/common/SelectBox.tsx
> +    background: ${theme.color.white};
억 항상 import만 해서 사용했는데 ThemeProvider를 통해 전역적으로 설정이 되어있었군요 ..? 
전부 수정 완료했습니다 갑사합니다 !

2024-04-15 17:51 UTC, hijiyun commented on src/components/common/SelectBox.tsx
> +  `,
넵 전부 수정 완료했어요 ! 완전히 까먹어버린 저의 기억 ..ㅎㅎ

2024-04-15 17:54 UTC, hijiyun commented on src/components/common/SelectBox.tsx
> +    line-height: normal;
아하 ..!! 감사합니다..!! 수정 완료했어요 
피그마에 있는거 전부 복사해오다 보니 이런 사단이 났네욥 ... 다음부터는 좀 더 생각하면서 작성하겠습니다 !

2024-04-15 18:06 UTC, sihyonn approved these changes

2024-04-15 18:17 UTC, hijiyun commented on src/components/common/SelectBox.tsx
> +  }, []);
시현님은 천재가 분명해요
시현님의 코드대로 했을때, 약간의 이슈가 좀 있어서 코드 참고 해서 다시 만들었어요 ! 
저는 ref가 두개라 배열로 담아서 보냈구요 ! 
시현님 덕분에 훅까지 만들어볼 수 있었네요 🤭

2024-04-15 18:20 UTC, hijiyun commented on src/components/common/SelectBox.tsx
> +  // whether가 false이고 선택된 옵션이 없으면 첫 번째 옵션을 선택한다.
whether가 "여부"라는 의미길래 사용했는데 이름만 보고는 파악하기 어려울수도 있겠군요 ..! 생각이 짧았습니다. 
placeholder의 여부이기 때문에 그냥 placeholder라는 네이밍이 훨씬 파악하기 쉬울 것 같아요! 일단 수정하도록 하겠습니다 !

2024-04-15 21:16 UTC, elenfl0122 approved these changes
너무 수고 많으셨어용!😌✨
지윤님 코드 보고 styled components 공부 많이 했습니당

2024-04-15 21:16 UTC, elenfl0122 commented on src/constants/MEDIAQUERIES.tsx
[P4]
: breackpoints랑  media query 상수로 만들어 두신거 너무 좋아요!👍🏻
그런데 이왕이면 두 객체 순서가 맞게 작성되면 더 보기 좋겠다는 저의 작은 소망..?🐮
`pc - tablet - mobile` 순서가 통일 되면 좋겠어요!!

2024-04-16 03:24 UTC, hyunjun9788 approved these changes

2024-04-16 03:24 UTC, hyunjun9788 commented on src/components/common/SelectBox.tsx
> +      )}
[P5]: 지윤님이 S 객체로 하신 거 보고 저도 해봤습니다! 굳굳

2024-04-16 04:10 UTC, hijiyun commented on src/constants/MEDIAQUERIES.tsx
넵 constants폴더에 만들어 뒀습니다 !

2024-04-16 04:13 UTC, merged